Prevent version conflict between "ftw.workspace" and "bumblebee.file".
Both packages require `ftw.file`, but `bumblebee.file` limits it to a very special range of releases. This caused the following error during `bin/buildout`:

```
While:
  Installing test.
Error: There is a version conflict.
We already have: ftw.file 2.3.1
but bumblebee.file 1.5.2 requires ‘ftw.file<2a,>=1.11.2’.
```