Pin ftw.calender to range because of conflict.
Version and requirements information containing ftw.calendar:
  Requirement of ftw.workspace: ftw.calendar
  Requirement of ftw.contentpage: ftw.calendarwidget
  Requirement of ftw.meeting[calendar,pdf,zipexport]: ftw.calendar<3,>=2.1.0
  Requirement of ftw.meeting[calendar,pdf,zipexport]: ftw.calendarwidget
  Requirement of ftw.calendar: plone.api
  Requirement of ftw.calendar: simplejson
  Requirement of ftw.calendar: ftw.upgrade
  Requirement of ftw.calendar: setuptools
  Requirement of ftw.calendar: Plone
  Requirement of ftw.calendarwidget: Products.Archetypes
  Requirement of ftw.calendarwidget: collective.js.jqueryui
  Requirement of ftw.calendarwidget: setuptools
While:
  Installing test.
Error: There is a version conflict.
We already have: ftw.calendar 3.1.2